### ISSUE TITLE
Future of this repo

### ISSUE THREAD

**Issue by mmaelicke** [VForWaTer/documentation#2]
The original idea for this repo was to compile the docs for V-FOR-WaTer in one place. So Code Reference, API, user guide: everything that is not already in the solo-packages (hydrobox, scikit-gstat etc.). Using only `.rst` or `.md` files would make it easy for the non-programmers in our team to contribute as well. 

Obviously we don't use it. 

I would like to make a decision if we want to keep this or not. To me keeping it like this does not really make sense. If we drop it, we should think about how to document then.

@MarcusStrobl @elnazazmi @joergmeyer-kit @sihassl keep or drop?

**Comment by MarcusStrobl** [comment]
Of course, we need some kind of documentation, and I think this solution is good. 
The reason nobody uses this one is that no one has time to write documentation. 
In my opinion the question shouldn't be "drop or not to drop" but "how many hours per week should we reserve to write docs".

**Comment by elnazazmi** [comment]
I think we should keep it. We have currently only one internal documentation and there is no other documentation for users. We need a manual for users.

**Comment by mmaelicke** [comment]
Glad that you see it similarly.

Then I will propose a Roadmap and coarse structure which you can comment. Finally I will reflect that in gh milestones with due date and we will see if that is enough pressure...

**Comment by mmaelicke** [comment]
I updated the repo and will send you a mail concerning the next steps.
